version: '3.5'

networks:
  redis-net:
    name: redis-net
    driver: bridge

services:
  redis-1:
    container_name: redis-1
    image: redis:4.0
    command: |
      --bind 0.0.0.0
      --cluster-enabled yes
      --port 7001
    ports:
    - 7001:7001
    networks:
    - redis-net

  redis-2:
    container_name: redis-2
    image: redis:4.0
    command: |
      --bind 0.0.0.0
      --cluster-enabled yes
      --port 7002
    ports:
    - 7002:7002
    networks:
    - redis-net

  redis-3:
    container_name: redis-3
    image: redis:4.0
    command: |
      --bind 0.0.0.0
      --cluster-enabled yes
      --port 7003
    ports:
    - 7003:7003
    networks:
    - redis-net

  redis-4:
    container_name: redis-4
    image: redis:4.0
    command: |
      --bind 0.0.0.0
      --cluster-enabled yes
      --port 7004
    ports:
    - 7004:7004
    networks:
    - redis-net

  redis-5:
    container_name: redis-5
    image: redis:4.0
    command: |
      --bind 0.0.0.0
      --cluster-enabled yes
      --port 7005
    ports:
    - 7005:7005
    networks:
    - redis-net

  redis-6:
    container_name: redis-6
    image: redis:4.0
    command: |
      --bind 0.0.0.0
      --cluster-enabled yes
      --port 7006
    ports:
    - 7006:7006
    networks:
    - redis-net
